language: python
python: 2.7

sudo: false

env:
    - TOXENV=py27
    - TOXENV=precise
    - TOXENV=py34
    - TOXENV=pypy

matrix:
    allow_failures:

        - env: TOXENV=py34
          python: 2.7

        - env: TOXENV=pypy
          python: 2.7

install:
    - pip install -U tox codecov

script:
    - tox

after_success:
    - codecov

notifications:
    irc:
        channels:
            - "irc.freenode.org#scrapy"
        use_notice: true
        skip_join: true
